spring.application.name=Embedding Model
spring.ai.ollama.embedding.model=bge-m3
spring.ai.ollama.base-url=http://host.docker.internal:11434 #docker
spring.ai.ollama.chat.model=qwen2.5:3b

server.port=8083