spring.application.name=rag-search-service
spring.ai.ollama.embedding.model=bge-m3
spring.ai.ollama.base-url=http://host.docker.internal:11434
spring.ai.ollama.chat.model=qwen2.5:3b

opensearch.host=opensearch
opensearch.port=9200
opensearch.index-name=rag-documents

server.port=8083