spring.application.name=Embedding Model
spring.ai.ollama.embedding.model=bge-m3
spring.ai.ollama.chat.model=qwen2.5:3b
spring.ai.ollama.base-url=http://localhost:11434

opensearch.host=localhost
opensearch.port=9200

server.port=8083